CREATE TABLE Etudiant (
      ETU VARCHAR(50) PRIMARY KEY,
      NOM VARCHAR(100)
);

CREATE TABLE AnneeScolaire(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(100),
    DATE_DEBUT DATE,
    DATE_FIN DATE,
    montantDroit DOUBLE
);


CREATE TABLE Ecolage(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ANNEE_SCOLAIRE INT,
    MONTANT_ANNUEL DOUBLE,
    FOREIGN KEY (ID_ANNEE_SCOLAIRE) REFERENCES ANNEESCOLAIRE(ID)

);

CREATE TABLE ModePaiement(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MODE VARCHAR(50) NOT NULL
);

CREATE TABLE ModePaiementEtudiant (
    ETU VARCHAR(50),
    ID_MODE_PAYEMENT INT NOT NULL,
    ID_ANNEE_SCOLAIRE INT,
    PRIMARY KEY (ETU,ID_ANNEE_SCOLAIRE),
    FOREIGN KEY (ETU) REFERENCES Etudiant(ETU),
    FOREIGN KEY (ID_MODE_PAYEMENT) REFERENCES ModePaiement(ID),
    FOREIGN KEY (ID_ANNEE_SCOLAIRE) REFERENCES AnneeScolaire(ID)
);


CREATE TABLE PayementEcolage(

    ID INT AUTO_INCREMENT PRIMARY KEY,
    ETU VARCHAR(50),
    ID_ANNEE_SCOLAIRE INT,
    MONTANT DOUBLE,
    RESTE DOUBLE DEFAULT 0,
    FOREIGN KEY (ETU) REFERENCES Etudiant(ETU),
    FOREIGN KEY (ID_ANNEE_SCOLAIRE) REFERENCES AnneeScolaire(ID)

);

CREATE TABLE PayementDroit(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ETU VARCHAR(50),
    ID_ANNEE_SCOLAIRE INT,
    DROIT DOUBLE,
    FOREIGN KEY (ETU) REFERENCES Etudiant(ETU),
    FOREIGN KEY (ID_ANNEE_SCOLAIRE) REFERENCES AnneeScolaire(ID)
);


DELETE FROM PayementDroit;
DELETE FROM PayementEcolage;
DELETE FROM ModePaiementEtudiant;
DELETE FROM ECOLAGE;
DELETE FROM AnneeScolaire;
